### ISSUE TITLE
Tech Service

### ISSUE THREAD

**Issue by EzraAmes** [niallrmurphy/twinslo#1]
Hello. 
I hope you are doing well.
My name is Ezra Ames and I found you on Github. 
I want to discuss something with you but when is convenient to communicate with you?

**Comment by niallrmurphy** [comment]
You can just send it here.

**Comment by EzraAmes** [comment]
I am from Mongolia and backend developer. 
I've been working as a web/blockchain developer on Upwork but my account is suddenly suspended for some reason. 
So I am looking for a collaborator.
My main skill is PHP and Node(especially nest.js) and have some good experiences in frontend building too.
I want to work with you. In a word, you can be a manager of me.
Otherwise, may I rent your upwork/freelancer account?
Of course, I will share the profit with you.
Please let me know what you think.
Thanks
